export const editorStyles = {
  editorContainer: {
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#f9f9f9',
    borderRadius: '8px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
    height: '100%',
    width: '100%',
    overflow: 'hidden',
  },
  editorWrapper: {
    width: '100%',
    maxWidth: '1000px',
    minHeight: 'calc(100vh - 250px)',
    maxHeight: 'calc(100vh - 250px)',
    border: '1px solid #ccc',
    padding: '10px',
    borderRadius: '4px',
    backgroundColor: '#fff',
    fontSize: '16px',
    lineHeight: '1.5',
    outline: 'none',
    overflow: 'auto',
  },
  suggestionsList: {
    position: 'absolute',
    zIndex: 10,
    width: '100%',
    maxWidth: '300px',
    minWidth: '100px',
    margin: '0', 
    padding: '0',
    listStyle: 'none',
    border: '1px solid #ccc',
    borderRadius: '4px',
    backgroundColor: '#fff',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
    maxHeight: '250px', 
    overflowY: 'auto', 
    fontSize: '14px',
  }, 
  suggestion: {
    padding: '10px',
    cursor: 'pointer',
    backgroundColor: '#fff',
    '&:hover': {
      backgroundColor: '#f0f0f0',
    },
  },
  suggestionHighlighted: {
    padding: '10px',
    backgroundColor: '#e0e0e0',
    cursor: 'pointer',
  },
  dateDisplay: {
    textAlign: "center",
    fontSize: "14px",
    fontWeight: "bold",
    color: "#555",
    margin: "10px 0",
  },
  saveButton: {
    alignSelf: "flex-end",
    marginTop: "5px",
    marginBottom: "5px",
    padding: "8px 16px",
    backgroundColor: "#007BFF",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "bold",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "#0056b3",
    },
    "&:active": {
      backgroundColor: "#004085",
    }
  },
  editorHeader: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: "10px",
  },
  titleInput: {
    width: '100%',
    maxWidth: '400px',
    padding: '10px',
    fontSize: '16px',
    border: '1px solid #ccc',
    borderRadius: '4px',
    boxSizing: 'border-box', 
  },
  titleDiv: {
    textAlign: "center",
    fontSize: "14px",
    fontWeight: "bold",
    margin: "10px 0",
  }
};
