export const suggestions = [
  "a warm apple",
  "apple", "appy", "apppyyyyy", 
  "banana", "blueberry", "blackberry", 
  "carrot", "cherry", "cucumber", 
  "date", "dragonfruit", "durian", 
  "egg", "elderberry", 
  "fig", "feijoa", 
  "grape", "guava", "gooseberry", 
  "honeydew", 
  "kiwi", "kumquat", 
  "lemon", "lime", 
  "mango", "melon", "mulberry", 
  "nectarine", 
  "orange", "olive", 
  "papaya", "peach", "pear", 
  "quince", 
  "raspberry", "rhubarb", 
  "strawberry", "starfruit", 
  "tangerine", "tomato", 
  "ugli", 
  "vanilla", 
  "watermelon", 
  "xigua", 
  "yam", 
  "zucchini",
  "fresh mango slice", 
  "sweet ripe pear", 
  "crunchy green apple", 
  "tart lemon zest", 
  "juicy watermelon chunk", 
  "tropical pineapple delight", 
  "delicious berry mix", 
  "chilled fruit salad", 
  "grilled peach slices", 
  "spicy tamarind chutney",
  "citrusy lime twist",
  "smooth avocado toast",
  "rich caramelized banana",
  "zesty lemon curd",
  "refreshing cucumber water",
  "sweet strawberry jam",
  "refreshing coconut water",
  "tangy orange juice",
  "crispy sweet potato fries",
  "roasted butternut squash",
  "exotic jackfruit flavor"
];
